# Generated by Django 4.2.3 on 2024-06-17 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departement', models.CharField(choices=[('Preparatory Classes', 'Preparatory Classes'), ('Master Common Teaching', 'Master Common Teaching'), ('Applied Statistics and Econometrics', 'Applied Statistics and Econometrics'), ('Finance and Actuarial', 'Finance and Actuarial'), ('Quantitative and Prospective Economics', 'Quantitative and Prospective Economics')], max_length=50)),
                ('departement_ar', models.CharField(choices=[('Preparatory Classes', 'Preparatory Classes'), ('Master Common Teaching', 'Master Common Teaching'), ('Applied Statistics and Econometrics', 'Applied Statistics and Econometrics'), ('Finance and Actuarial', 'Finance and Actuarial'), ('Quantitative and Prospective Economics', 'Quantitative and Prospective Economics')], max_length=50, null=True)),
                ('departement_en', models.CharField(choices=[('Preparatory Classes', 'Preparatory Classes'), ('Master Common Teaching', 'Master Common Teaching'), ('Applied Statistics and Econometrics', 'Applied Statistics and Econometrics'), ('Finance and Actuarial', 'Finance and Actuarial'), ('Quantitative and Prospective Economics', 'Quantitative and Prospective Economics')], max_length=50, null=True)),
                ('departement_fr', models.CharField(choices=[('Preparatory Classes', 'Preparatory Classes'), ('Master Common Teaching', 'Master Common Teaching'), ('Applied Statistics and Econometrics', 'Applied Statistics and Econometrics'), ('Finance and Actuarial', 'Finance and Actuarial'), ('Quantitative and Prospective Economics', 'Quantitative and Prospective Economics')], max_length=50, null=True)),
                ('name', models.CharField(max_length=50)),
                ('name_ar', models.CharField(max_length=50, null=True)),
                ('name_en', models.CharField(max_length=50, null=True)),
                ('name_fr', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=30)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('photo', models.ImageField(null=True, upload_to='media/photoDepartement/')),
            ],
        ),
        migrations.CreateModel(
            name='DepartementEconomieQuntitative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Headdepartement', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=30)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('photo', models.ImageField(null=True, upload_to='media/photoDepartement/')),
                ('comment', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DepartementEnseignementCommun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Headdepartement', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=30)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('photo', models.ImageField(null=True, upload_to='media/photoDepartement/')),
                ('comment', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DepartementFinance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Headdepartement', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=30)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('photo', models.ImageField(null=True, upload_to='media/photoDepartement/')),
                ('comment', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DepartementPrepa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Headdepartement', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=30)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('photo', models.ImageField(null=True, upload_to='media/photoDepartement/')),
                ('discription', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DepartementStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Headdepartement', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=30)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('photo', models.ImageField(null=True, upload_to='media/photoDepartement/')),
                ('comment', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=70)),
                ('title_ar', models.TextField(max_length=70, null=True)),
                ('title_en', models.TextField(max_length=70, null=True)),
                ('title_fr', models.TextField(max_length=70, null=True)),
                ('image', models.ImageField(upload_to='media/event/')),
                ('comment', models.TextField()),
                ('comment_ar', models.TextField(null=True)),
                ('comment_en', models.TextField(null=True)),
                ('comment_fr', models.TextField(null=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
