# Generated by Django 4.2.3 on 2024-06-18 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnnseaSite', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Departement',
        ),
        migrations.RenameField(
            model_name='departementeconomiequntitative',
            old_name='comment',
            new_name='discription',
        ),
        migrations.RenameField(
            model_name='departementenseignementcommun',
            old_name='comment',
            new_name='discription',
        ),
        migrations.RenameField(
            model_name='departementfinance',
            old_name='comment',
            new_name='discription',
        ),
        migrations.RenameField(
            model_name='departementstat',
            old_name='comment',
            new_name='discription',
        ),
        migrations.AddField(
            model_name='departementeconomiequntitative',
            name='Headdepartement_ar',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='departementeconomiequntitative',
            name='Headdepartement_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='departementeconomiequntitative',
            name='Headdepartement_fr',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='departementeconomiequntitative',
            name='discription_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='departementeconomiequntitative',
            name='discription_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='departementeconomiequntitative',
            name='discription_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='departementenseignementcommun',
            name='Headdepartement_ar',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='departementenseignementcommun',
            name='Headdepartement_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='departementenseignementcommun',
            name='Headdepartement_fr',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='departementenseignementcommun',
            name='discription_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='departementenseignementcommun',
            name='discription_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='departementenseignementcommun',
            name='discription_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='departementfinance',
            name='Headdepartement_ar',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='departementfinance',
            name='Headdepartement_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='departementfinance',
            name='Headdepartement_fr',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='departementfinance',
            name='discription_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='departementfinance',
            name='discription_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='departementfinance',
            name='discription_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='departementprepa',
            name='Headdepartement_ar',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='departementprepa',
            name='Headdepartement_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='departementprepa',
            name='Headdepartement_fr',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='departementprepa',
            name='discription_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='departementprepa',
            name='discription_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='departementprepa',
            name='discription_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='departementstat',
            name='Headdepartement_ar',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='departementstat',
            name='Headdepartement_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='departementstat',
            name='Headdepartement_fr',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='departementstat',
            name='discription_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='departementstat',
            name='discription_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='departementstat',
            name='discription_fr',
            field=models.TextField(null=True),
        ),
    ]
