# Generated by Django 4.2.3 on 2024-06-21 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnnseaSite', '0002_delete_departement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleMasterSpeciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speciality', models.CharField(max_length=30)),
                ('modules', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ModulePrepaMasterCommun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anne', models.CharField(max_length=30)),
                ('modules', models.TextField()),
            ],
        ),
    ]
