# Generated by Django 4.2.3 on 2024-06-22 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnnseaSite', '0004_modulemasterspeciality_modules_ar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulemasterspeciality',
            name='speciality',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='modulemasterspeciality',
            name='speciality_ar',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='modulemasterspeciality',
            name='speciality_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='modulemasterspeciality',
            name='speciality_fr',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
