# Generated by Django 4.2.3 on 2024-06-22 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnnseaSite', '0005_alter_modulemasterspeciality_speciality_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleMasterDepFinance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speciality', models.CharField(max_length=50)),
                ('speciality_ar', models.CharField(max_length=50, null=True)),
                ('speciality_en', models.CharField(max_length=50, null=True)),
                ('speciality_fr', models.CharField(max_length=50, null=True)),
                ('modules', models.TextField()),
                ('modules_ar', models.TextField(null=True)),
                ('modules_en', models.TextField(null=True)),
                ('modules_fr', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModuleMasterDepStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speciality', models.CharField(max_length=50)),
                ('speciality_ar', models.CharField(max_length=50, null=True)),
                ('speciality_en', models.CharField(max_length=50, null=True)),
                ('speciality_fr', models.CharField(max_length=50, null=True)),
                ('modules', models.TextField()),
                ('modules_ar', models.TextField(null=True)),
                ('modules_en', models.TextField(null=True)),
                ('modules_fr', models.TextField(null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='ModuleMasterSpeciality',
            new_name='ModuleMasterDepEconomQunttv',
        ),
        migrations.RenameField(
            model_name='moduleprepamastercommun',
            old_name='anne',
            new_name='annee',
        ),
        migrations.RenameField(
            model_name='moduleprepamastercommun',
            old_name='anne_ar',
            new_name='annee_ar',
        ),
        migrations.RenameField(
            model_name='moduleprepamastercommun',
            old_name='anne_en',
            new_name='annee_en',
        ),
        migrations.RenameField(
            model_name='moduleprepamastercommun',
            old_name='anne_fr',
            new_name='annee_fr',
        ),
    ]
