# Generated by Django 4.2.3 on 2024-06-24 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EnnseaSite', '0007_alter_moduleprepamastercommun_annee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnterpreneurShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='EnterpreneurShipPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/EnterpreneurShipPhotos/')),
                ('enterpreneurShip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='EnnseaSite.enterpreneurship')),
            ],
        ),
    ]
