# Generated by Django 4.2.3 on 2024-06-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnnseaSite', '0008_enterpreneurship_enterpreneurshipphotos'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterpreneurship',
            name='description_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='enterpreneurship',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='enterpreneurship',
            name='description_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='enterpreneurship',
            name='image',
            field=models.ImageField(null=True, upload_to='media/EnterpreneurShipPhotos/'),
        ),
        migrations.AddField(
            model_name='enterpreneurship',
            name='image1',
            field=models.ImageField(null=True, upload_to='media/EnterpreneurShipPhotos/'),
        ),
        migrations.AddField(
            model_name='enterpreneurship',
            name='image2',
            field=models.ImageField(null=True, upload_to='media/EnterpreneurShipPhotos/'),
        ),
        migrations.AddField(
            model_name='enterpreneurship',
            name='title_ar',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='enterpreneurship',
            name='title_en',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='enterpreneurship',
            name='title_fr',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='EnterpreneurShipPhotos',
        ),
    ]
