# Generated by Django 4.2.3 on 2024-06-30 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnnseaSite', '0009_enterpreneurship_description_ar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biblio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directeur', models.CharField(max_length=60, null=True)),
                ('emailDirectr', models.EmailField(max_length=254, null=True)),
                ('phonDirectr', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoBiblio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(null=True, upload_to='media/photoLibrary')),
                ('caption', models.CharField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SplideHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='media/splideHome')),
                ('caption', models.CharField(null=True)),
            ],
        ),
    ]
