# Generated by Django 4.2.3 on 2024-06-30 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnnseaSite', '0010_biblio_photobiblio_splidehome'),
    ]

    operations = [
        migrations.AddField(
            model_name='biblio',
            name='reglement',
            field=models.FileField(blank=True, null=True, upload_to='media/pdf_files'),
        ),
    ]
