# Generated by Django 4.2.3 on 2024-07-09 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnnseaSite', '0013_departements'),
    ]

    operations = [
        migrations.AddField(
            model_name='departements',
            name='Headdepartement_ar',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='departements',
            name='Headdepartement_en',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='departements',
            name='Headdepartement_fr',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='departements',
            name='discription_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='departements',
            name='discription_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='departements',
            name='discription_fr',
            field=models.TextField(null=True),
        ),
    ]
