# Generated by Django 4.2.3 on 2024-07-10 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnnseaSite', '0015_delete_departementeconomiequntitative_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speciality', models.CharField(choices=[('Applied Statistics', 'Applied Statistics'), ('Applied EconomicsProspective', 'Applied Economics Prospective'), ('Finance', 'Finance'), ('Data Science', 'Data Science'), ('Economic Prospective', 'Economic Prospective'), ('Population and Social Statistics', 'Population and  Social Statistics')], max_length=40)),
                ('annee', models.CharField(max_length=50)),
                ('modules', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='departements',
            name='dprtmnt',
            field=models.CharField(choices=[('preparatoire', 'preparatoire'), ('commun', 'commun'), ('statistique', 'statistique'), ('finance', 'finance'), ('economieQunttv', 'economieQunttv')], max_length=30),
        ),
    ]
