# Generated by Django 4.2.3 on 2024-07-10 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnnseaSite', '0017_alter_modules_speciality'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules',
            name='annee_ar',
            field=models.CharField(blank=True, choices=[('Annee_1', 'Annee_1'), ('Annee_2', 'Annee_2')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='modules',
            name='annee_en',
            field=models.CharField(blank=True, choices=[('Annee_1', 'Annee_1'), ('Annee_2', 'Annee_2')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='modules',
            name='annee_fr',
            field=models.CharField(blank=True, choices=[('Annee_1', 'Annee_1'), ('Annee_2', 'Annee_2')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='modules',
            name='modules_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='modules',
            name='modules_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='modules',
            name='modules_fr',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='modules',
            name='annee',
            field=models.CharField(blank=True, choices=[('Annee_1', 'Annee_1'), ('Annee_2', 'Annee_2')], max_length=50, null=True),
        ),
    ]
