# Generated by Django 4.2.3 on 2024-07-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnnseaSite', '0018_modules_annee_ar_modules_annee_en_modules_annee_fr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modules',
            name='annee_ar',
        ),
        migrations.RemoveField(
            model_name='modules',
            name='annee_en',
        ),
        migrations.RemoveField(
            model_name='modules',
            name='annee_fr',
        ),
        migrations.AlterField(
            model_name='modules',
            name='annee',
            field=models.CharField(blank=True, choices=[('Annee_1', 'Annee_1'), ('Annee_2', 'Annee_2')], max_length=30, null=True),
        ),
    ]
