# Generated by Django 4.2.3 on 2024-07-13 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EnnseaSite', '0020_delete_moduleprepamastercommun_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModuleMasterDepEconomQunttv',
        ),
        migrations.DeleteModel(
            name='ModuleMasterDepFinance',
        ),
        migrations.DeleteModel(
            name='ModuleMasterDepStat',
        ),
    ]
