# Generated by Django 4.2.3 on 2024-07-16 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EnnseaSite', '0021_delete_modulemasterdepeconomqunttv_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembrLaboRech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('name_ar', models.CharField(max_length=100, null=True)),
                ('name_en', models.CharField(max_length=100, null=True)),
                ('name_fr', models.CharField(max_length=100, null=True)),
                ('grade', models.CharField(max_length=70, null=True)),
                ('grade_ar', models.CharField(max_length=70, null=True)),
                ('grade_en', models.CharField(max_length=70, null=True)),
                ('grade_fr', models.CharField(max_length=70, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LaboRech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laboName', models.CharField(max_length=120)),
                ('laboName_ar', models.CharField(max_length=120, null=True)),
                ('laboName_en', models.CharField(max_length=120, null=True)),
                ('laboName_fr', models.CharField(max_length=120, null=True)),
                ('laboDescrp', models.TextField(null=True)),
                ('laboDescrp_ar', models.TextField(null=True)),
                ('laboDescrp_en', models.TextField(null=True)),
                ('laboDescrp_fr', models.TextField(null=True)),
                ('membrLabo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EnnseaSite.membrlaborech')),
            ],
        ),
    ]
