# Generated by Django 4.2.3 on 2024-07-17 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnnseaSite', '0022_membrlaborech_laborech'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laborech',
            name='membrLabo',
        ),
        migrations.AddField(
            model_name='laborech',
            name='membrLabo',
            field=models.ManyToManyField(to='EnnseaSite.membrlaborech'),
        ),
    ]
