# Generated by Django 4.2.3 on 2024-07-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnnseaSite', '0023_remove_laborech_membrlabo_laborech_membrlabo'),
    ]

    operations = [
        migrations.CreateModel(
            name='convention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, null=True)),
                ('title_ar', models.CharField(max_length=120, null=True)),
                ('title_en', models.CharField(max_length=120, null=True)),
                ('title_fr', models.CharField(max_length=120, null=True)),
                ('photo', models.ImageField(null=True, upload_to='media/convnetion')),
                ('discription', models.TextField(null=True)),
                ('discription_ar', models.TextField(null=True)),
                ('discription_en', models.TextField(null=True)),
                ('discription_fr', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RelationsExtr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presentation', models.TextField(null=True)),
                ('presentation_ar', models.TextField(null=True)),
                ('presentation_en', models.TextField(null=True)),
                ('presentation_fr', models.TextField(null=True)),
                ('headDepartment', models.CharField(max_length=60)),
                ('headDepartment_ar', models.CharField(max_length=60, null=True)),
                ('headDepartment_en', models.CharField(max_length=60, null=True)),
                ('headDepartment_fr', models.CharField(max_length=60, null=True)),
                ('Phone', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
        ),
    ]
