# Generated by Django 4.2.3 on 2024-07-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnnseaSite', '0024_convention_relationsextr'),
    ]

    operations = [
        migrations.AddField(
            model_name='convention',
            name='typeConv',
            field=models.CharField(choices=[('national convention', 'national convention'), ('international conventions', 'international conventions')], null=True),
        ),
    ]
