# Generated by Django 4.2.3 on 2024-07-22 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnnseaSite', '0025_convention_typeconv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convention',
            name='discription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='convention',
            name='discription_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='convention',
            name='discription_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='convention',
            name='discription_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='convention',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/convnetion'),
        ),
    ]
