# Generated by Django 4.2.3 on 2024-07-24 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnnseaSite', '0027_remove_convention_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileServiceStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(null=True)),
                ('file', models.FileField(null=True, upload_to='PDFs', verbose_name='file to download')),
            ],
        ),
        migrations.CreateModel(
            name='serviceStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presentation', models.TextField()),
                ('titel', models.CharField(null=True)),
                ('ProgrmSoutenance', models.FileField(null=True, upload_to='PDFs', verbose_name='Planning de Soutenances')),
                ('DateSoutenance', models.DateField(null=True, verbose_name='Date de Planning de soutenenace')),
            ],
        ),
    ]
