# Generated by Django 4.2.3 on 2024-07-25 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnnseaSite', '0030_alter_fileservicestage_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicestage',
            name='ProgrmSoutenance',
            field=models.FileField(blank=True, null=True, upload_to='PDFs', verbose_name='Planning de Soutenances'),
        ),
    ]
